version: "3.7"
services:
#  your_service:
#    build:
#      context: .
#      target: production
#    networks:
#      - rabbitmq_net
  rabbitmq:
    image: rabbitmq:3.8-management
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./.docker/rabbitmq/data:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/log:/var/log/rabbitmq/
    networks:
      - rabbitmq_net

networks:
  rabbitmq_net:
    driver: bridge
